/* eslint no-use-before-define: 0 */ // --> OFF

// APPEND REDUCERS HERE (content generated by plopfile, do not remove comment)

// APPEND NAMESPACES HERE (content generated by plopfile, do not remove comment)

export default {
  // APPEND EXPORTS HERE (content generated by plopfile, do not remove comment)
};
